[Interface]
PrivateKey = AM55UDvZRur6ConLMo0quaETwpnXGSK4fPvJi7T3nng=
Address = 10.104.5.223/32
DNS = 1.1.1.1, 8.8.8.8

[Peer]
PublicKey = Fwt2sU9t7zRQye4BP/5IsO3dZjvRVR5hO5JD+6JFAEs=
Endpoint = 51.75.145.20:443
AllowedIPs = 0.0.0.0/0, ::/0
PersistentKeepalive = 25
